name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies 📦
        working-directory: ./src/AntDesign.Charts/wwwroot
        run: npm install

      - name: Run JavaScript Tests 🧪
        working-directory: ./src/AntDesign.Charts/wwwroot
        run: npm run test:ci

      - name: Build Project 🏗
        run: dotnet build
